"""empty message

Revision ID: 1f3c0da9559
Revises: 2e6234de1f78
Create Date: 2014-02-28 15:14:36.990940

"""

# revision identifiers, used by Alembic.
revision = '1f3c0da9559'
down_revision = '2e6234de1f78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    ### end Alembic commands ###
