"""empty message

Revision ID: 2e6234de1f78
Revises: 501d8c90c4da
Create Date: 2014-02-28 10:25:25.970180

"""

# revision identifiers, used by Alembic.
revision = '2e6234de1f78'
down_revision = '501d8c90c4da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
