"""empty message

Revision ID: 361046d7b4b0
Revises: None
Create Date: 2014-02-27 16:04:10.035645

"""

# revision identifiers, used by Alembic.
revision = '361046d7b4b0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
